
import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Share2, Download, Check } from 'lucide-react';
import { TopicData } from '../types';
import { getIcon } from '../constants';
import CongestionSimulation from './visualizations/CongestionSimulation';
import RingAllReduce from './visualizations/RingAllReduce';
import RDMAQueuePair from './visualizations/RDMAQueuePair';
import P4Pipeline from './visualizations/P4Pipeline';

interface TopicContentProps {
  data: TopicData;
}

const QASection: React.FC<{ question: string; answer: string }> = ({ question, answer }) => {
  const [userAnswer, setUserAnswer] = useState('');
  const [showAnswer, setShowAnswer] = useState(false);

  return (
    <div className="mt-8 bg-slate-100 dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800">
      <h3 className="text-lg font-bold text-slate-800 dark:text-slate-200 mb-2">Check Your Knowledge</h3>
      <p className="text-slate-600 dark:text-slate-400 mb-4">{question}</p>
      
      <textarea
        className="w-full p-3 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200 focus:ring-2 focus:ring-indigo-500 focus:outline-none mb-3 transition-colors"
        rows={3}
        placeholder="Type your answer here..."
        value={userAnswer}
        onChange={(e) => setUserAnswer(e.target.value)}
      />
      
      <div className="flex gap-3">
        <button 
          onClick={() => setShowAnswer(!showAnswer)}
          className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium transition"
        >
          {showAnswer ? 'Hide Answer' : 'Show Answer'}
        </button>
      </div>

      {showAnswer && (
        <div className="mt-4 p-4 bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-lg animate-in fade-in slide-in-from-top-2">
          <p className="font-semibold text-emerald-800 dark:text-emerald-400 text-sm mb-1">Model Answer:</p>
          <p className="text-slate-700 dark:text-slate-300">{answer}</p>
        </div>
      )}
    </div>
  );
};

const TopicContent: React.FC<TopicContentProps> = ({ data }) => {
  const [copied, setCopied] = useState(false);

  const renderVisualization = () => {
    switch(data.visualizationType) {
      case 'congestion': return <CongestionSimulation />;
      case 'ring': return <RingAllReduce />;
      case 'rdma_qp': return <RDMAQueuePair />;
      case 'p4_pipeline': return <P4Pipeline />;
      default: return null;
    }
  };

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleExport = () => {
    const header = `${data.title}\n${data.description}\n\n`;
    const body = data.sections.map(s => `### ${s.title}\n\n${s.content}\n\n`).join('');
    const footer = `\n\nGenerated by NetLearn`;
    const text = header + body + footer;
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NetLearn-${data.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto pb-20">
      <div className="mb-8 border-b border-slate-200 dark:border-slate-800 pb-6">
        <div className="flex justify-between items-start">
           <div>
              <div className="w-12 h-12 bg-indigo-600 rounded-xl flex items-center justify-center text-white mb-4 shadow-lg shadow-indigo-200 dark:shadow-none">
                {getIcon(data.icon, { size: 24 })}
              </div>
              <h1 className="text-4xl font-bold text-slate-900 dark:text-slate-50 tracking-tight mb-2">{data.title}</h1>
              <p className="text-xl text-slate-500 dark:text-slate-400 font-light">{data.description}</p>
           </div>
           
           <div className="flex gap-2">
             <button 
              onClick={handleShare}
              className="p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-500 hover:text-indigo-600 hover:border-indigo-600 transition flex items-center gap-2 group"
              title="Copy Link"
             >
               {copied ? <Check size={18} className="text-emerald-500" /> : <Share2 size={18} />}
               <span className="text-xs font-medium hidden group-hover:block">{copied ? 'Copied' : 'Share'}</span>
             </button>
             <button 
              onClick={handleExport}
              className="p-2 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-500 hover:text-indigo-600 hover:border-indigo-600 transition flex items-center gap-2 group"
              title="Export as TXT"
             >
               <Download size={18} />
               <span className="text-xs font-medium hidden group-hover:block">Export</span>
             </button>
           </div>
        </div>
      </div>

      {data.visualizationType !== 'none' && (
        <div className="mb-10 animate-in fade-in slide-in-from-bottom-4 duration-700">
          {renderVisualization()}
        </div>
      )}

      <div className="space-y-12 mb-16">
        {data.sections.map((section, idx) => (
          <section key={idx} className="animate-in fade-in slide-in-from-bottom-8 duration-700" style={{ animationDelay: `${idx * 100}ms` }}>
            <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100 mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-indigo-500 rounded-full inline-block"></span>
              {section.title}
            </h2>
            <div className="prose prose-lg prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-300">
              <ReactMarkdown
                components={{
                    code: ({ node, className, children, ...props }: any) => {
                        const match = /language-(\w+)/.exec(className || '');
                        const isInline = !match;
                        return isInline ? (
                          <code className="bg-slate-100 dark:bg-slate-800 text-pink-600 dark:text-pink-400 px-1.5 py-0.5 rounded text-sm font-mono font-medium">
                            {children}
                          </code>
                        ) : (
                          <code className={`${className || ''} block bg-slate-900 text-slate-50 p-4 rounded-lg my-4 overflow-x-auto border border-slate-800 font-mono text-sm`}>
                            {children}
                          </code>
                        );
                    },
                    a: ({ href, children, ...props }: any) => {
                        return (
                          <a 
                            href={href}
                            className="text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 dark:hover:text-indigo-300 underline" 
                            target="_blank" 
                            rel="noopener noreferrer"
                          >
                            {children}
                          </a>
                        );
                    }
                }}
              >
                {section.content}
              </ReactMarkdown>
            </div>
            {section.qna && (
              <QASection question={section.qna.question} answer={section.qna.answer} />
            )}
          </section>
        ))}
      </div>

      <div className="mt-24 pt-8 border-t border-slate-200 dark:border-slate-800 flex flex-col items-center gap-2 text-sm text-slate-500 dark:text-slate-500">
        <p>&copy; Noam Gold AI 2025</p>
        <a href="mailto:gold.noam@gmail.com" className="text-indigo-600 dark:text-indigo-400 hover:underline hover:text-indigo-700 transition-colors">
          Send Feedback
        </a>
      </div>
    </div>
  );
};

export default TopicContent;
